//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorias_Libros
    {
        public int id_categorias_libros { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public string id_libros { get; set; }
    
        public virtual Categorias Categoria { get; set; }
        public virtual Libros Libro { get; set; }
    }
}
