//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libros()
        {
            this.Autores_Libros = new HashSet<Autores_Libros>();
            this.Categorias_Libros = new HashSet<Categorias_Libros>();
            this.Prestamos = new HashSet<Prestamos>();
            this.Reservas = new HashSet<Reservas>();
        }
    
        public string id_libros { get; set; }
        public string isbn { get; set; }
        public string titulo { get; set; }
        public string subtitulo { get; set; }
        public Nullable<System.DateTime> fechaPublicacion { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> nPaginas { get; set; }
        public string imagen { get; set; }
        public string editorial { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<bool> reservado { get; set; }
        public Nullable<bool> prestado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Autores_Libros> Autores_Libros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categorias_Libros> Categorias_Libros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamos> Prestamos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
