//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int id_reserva { get; set; }
        public string id_libros { get; set; }
        public string dni { get; set; }
        public Nullable<int> num_cola { get; set; }
    
        public virtual Libros Libro { get; set; }
        public virtual Usuarios Usuario { get; set; }
    }
}
