
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BiblioAstur
{

using System;
    
public partial class SeleccionarPrestamosDTO
{

    public System.Guid id_prestamo { get; set; }

    public string isbn { get; set; }

    public string dni { get; set; }

    public Nullable<System.DateTime> fechaPrestamo { get; set; }

    public Nullable<System.DateTime> fechaEntrega { get; set; }

    public Nullable<System.DateTime> fechaDevolucion { get; set; }

    public Nullable<bool> fechaInvalida { get; set; }

}

}
