
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BiblioAstur
{

using System;
    
public partial class SeleccionarAutoresLibroDTO
{

    public Nullable<System.Guid> id_autor { get; set; }

    public string isbn { get; set; }

}

}
