
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BiblioAstur
{

using System;
    
public partial class SeleccionarUsuariosDTO
{

    public string dni { get; set; }

    public string nombre { get; set; }

    public string apellidos { get; set; }

    public string direccion { get; set; }

    public string telefono { get; set; }

    public string email { get; set; }

    public string usuario { get; set; }

    public Nullable<bool> admin { get; set; }

    public Nullable<System.DateTime> fechaNacimiento { get; set; }

}

}
