
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BiblioAstur
{

using System;
    
public partial class SeleccionarLibrosDTO
{

    public string isbn { get; set; }

    public string titulo { get; set; }

    public string subtitulo { get; set; }

    public System.DateTime fechaPublicacion { get; set; }

    public string editorial { get; set; }

    public string descripcion { get; set; }

    public int nPaginas { get; set; }

    public string imagen { get; set; }

    public int stock { get; set; }

    public bool reservado { get; set; }

    public bool prestado { get; set; }

    public System.Guid id_autor { get; set; }

    public string nombre { get; set; }

    public string apellidos { get; set; }

    public System.Guid id_categoria { get; set; }

    public string categoria { get; set; }

}

}
